spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog      # MySQL 접속 계정명
    password: tnghd7889   # MySQL 접속 비밀번호

  jpa:
    hibernate:
      ddl-auto: update   # 개발 시 update, 운영은 validate 권장.
      dialect: org.hibernate.dialect.MySQL8Dialect   # ← 추가!
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy-client-id
            client-secret: dummy-client-secret
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: c3R1ZHktc3ByaW5nYm9vdA==
